# Generated by Django 6.0.6 on 2026-06-30 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.PositiveSmallIntegerField(default=20)),
                ('days', models.CharField(blank=True, max_length=40)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athletes', models.ManyToManyField(blank=True, related_name='batches', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('coach', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('source', models.CharField(choices=[('coach', 'Marked by Coach'), ('self_qr', 'Self (QR)'), ('self_geo', 'Self (Geofence)'), ('self', 'Self')], default='coach', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='athletes.athleteprofile')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='coaching.batch')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='coaching_at_date_405ac6_idx'), models.Index(fields=['athlete', 'date'], name='coaching_at_athlete_f1d461_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'batch', 'date'), name='unique_attendance_per_day')],
            },
        ),
    ]
