# Generated by Django 6.0.6 on 2026-06-30 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaching', '0002_batch_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rifle', 'Air Rifle'), ('pistol', 'Air Pistol'), ('cylinder', 'Compressed Air Cylinder'), ('jacket', 'Jacket'), ('trouser', 'Trousers'), ('other', 'Other')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('cylinder_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kit', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('coach', 'athlete', 'period')},
            },
        ),
    ]
