# Generated by Django 6.0.6 on 2026-06-30 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaching', '0002_batch_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cycle', models.CharField(choices=[('macro', 'Macrocycle'), ('meso', 'Mesocycle')], default='meso', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('themes', models.TextField(blank=True, help_text='Technical themes, competition peaks, goals')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plans', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=120)),
                ('drills', models.TextField(blank=True, help_text='Holding drills, dry firing, match sim, etc.')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='coaching.coachprofile')),
                ('course_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.courseplan')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='training_tr_athlete_086c2e_idx')],
            },
        ),
    ]
