# Generated by Django 6.0.6 on 2026-06-30 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['state', 'name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting_assoc_id', models.CharField(blank=True, help_text='Optional National/State association ID', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('dominant_hand', models.CharField(blank=True, choices=[('RH', 'Right Hand'), ('LH', 'Left Hand')], max_length=2)),
                ('dominant_eye', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('cross', 'Cross-Dominant')], max_length=10)),
                ('discipline', models.CharField(blank=True, choices=[('air_rifle', '10m Air Rifle'), ('air_pistol', '10m Air Pistol')], max_length=20)),
                ('diet_type', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian')], max_length=20)),
                ('current_tier', models.CharField(choices=[('rookie', 'Rookie'), ('novice', 'Novice'), ('marksman', 'Marksman'), ('sharpshooter', 'Sharpshooter'), ('district', 'District / Pre-State Qualified'), ('state', 'State Qualified'), ('zone', 'Zone Qualified'), ('national', 'National Qualified'), ('trial', 'Trial Qualified'), ('national_team', 'National Team Qualified')], default='rookie', max_length=20)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='coaching.coachprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='coaching.parentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='athletes.club')),
            ],
        ),
        migrations.CreateModel(
            name='CoachAthleteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_links', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_links', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('athlete', 'coach'), name='unique_pending_link_per_pair')],
            },
        ),
    ]
