# Generated by Django 6.0.6 on 2026-06-30 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaching', '0002_batch_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial', 'Initial Evaluation'), ('periodic', 'Periodic Evaluation')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('hold_stability', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('trigger_timing', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('approach', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('follow_through', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('core_strength', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cardio_endurance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('balance_index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='athletes.athleteprofile')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='coaching.coachprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('sleep_quality', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, help_text='bpm', null=True)),
                ('stress_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='athletes.athleteprofile')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='unique_diary_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ShootingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_shots', models.PositiveSmallIntegerField(default=0)),
                ('inner_tens', models.PositiveSmallIntegerField(default=0, help_text='10.3+ shots')),
                ('grouping_mm', models.FloatField(blank=True, help_text='Group size (mm)', null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('target_file', models.FileField(blank=True, help_text='SCATT / Meyton export', null=True, upload_to='shooting/targets/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_records', to='athletes.athleteprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='performance_athlete_8cb123_idx')],
            },
        ),
    ]
